Add Wiilink WFC Patcher
OpenShopChannel/Apps pull request #78
Opened 2024-07-23 06:20 UTC by playerjmr

- [ ] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [ ] Have you verified that the manifest contains valid JSON?
- [ ] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [ ] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

This is the Wiilink WFC Disc Patcher. I had permission from mkwcat to add this to OSC

2024-07-24 18:15 UTC, GabubuAvailable requested changes

2024-07-24 18:15 UTC, GabubuAvailable commented on contents/WiiLink WFC Patcher.oscmeta
> +        "location": "https://wfc.wiilink24.com/patcher/WiiLink%20WFC%20Patcher.zip",
here you need to remove that comma (line 13)

2024-07-24 18:15 UTC, GabubuAvailable commented on contents/WiiLink WFC Patcher.oscmeta
> +        }
you forgot to add a comma here (line 18)

2024-08-07 13:46 UTC, emilydaemon approved these changes
should be valid JSON now

2024-08-07 13:48 UTC, merged