Add Newo Bit and Cheat Manager
OpenShopChannel/Apps pull request #91
Opened 2024-09-08 04:52 UTC by playerjmr

- [ ] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [ ] Have you verified that the manifest contains valid JSON?
- [ ] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [ ] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?

Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this location.

---

Newo Bit is a puzzle game created by [Owen](https://owensoft.net/project/newogame/) in which you place planets in orbit.
Cheat Manager is a utility that allows you to write, edit, and manage cheat code text files and even convert them to a usable GCT format for your games directly from the Wii console.

2024-09-17 17:28 UTC, GabubuAvailable commented on contents/cheat-manager.oscmeta
> +        "location": "https://wiibrew.org/w/images/c/c7/Cheat_manager_v0_3.rar",
remove the comma from line 20

2024-09-17 17:29 UTC, GabubuAvailable commented on contents/cheat-manager.oscmeta
> +    },
remove the comma from line 21

2024-09-17 17:30 UTC, GabubuAvailable commented on contents/newobit.oscmeta
> +        "location": "https://owensoft.net/project/newogame/dl/newobit.zip",
remove the comma from line 23

2024-09-17 17:31 UTC, GabubuAvailable requested changes
Please consider fixing them before merging. Thanks!

2024-09-21 20:01 UTC, GabubuAvailable approved these changes

2024-09-21 20:01 UTC, merged

2024-09-22 01:06 UTC, Artuto commented
For the record, the manifest for Cheat Manager was wrong, folder names must be the same as the app slug.